esphome:
  name: solarrouter
  friendly_name: SolarRouter
  min_version: 2025.9.0
  name_add_mac_suffix: false

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
  level: DEBUG
  logs:
      # Masque les logs détaillés du Modbus (requêtes/réponses)
      modbus: ERROR
      modbus_controller: ERROR
      modbus_controller.sensor: ERROR
#      sensor: ERROR
      
# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
- platform: esphome
- platform: web_server

web_server:
  port: 80
  
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

packages:
  solar_router:
    url: https://github.com/M3c4tr0x/Solar-Router-for-ESPHome/
    refresh: 1s
    files: 
      - path: solar_router/common.yaml 

      # gestion du JSY-MK-194T
      - path: solar_router/jsy-mk-194t_common.yaml
        vars:          
          uart_tx_pin: GPIO26
          uart_rx_pin: GPIO27
          uart_baud_rate: 4800
          AP_Ch2_internal: "false"

      # mesure d'energie dérivé via JSY-MK-194T
      - path: solar_router/energy_counter_jsy-mk-194t.yaml

      # en mode automatique et en ayant configuré un JSY-MK-194T pour le calcul de l'energie dérivée, mesure de puissance échangé 
      # avec le réseau via home assistant ( cas où le JSY n'a pas accès à la mesure, ou si on est en 0 injection)
      - path: solar_router/power_meter_home_assistant_with_energy_counter_jsy-mk-194t.yaml
        vars:
          main_power_sensor: sensor.puissance_soutiree_reseau_simulee_prevision_filtree_2
          consumption_sensor: sensor.inverter_activepower_load_sys

      - path: solar_router/regulator_triac.yaml
        vars:
          regulator_gate_pin: GPIO22
          regulator_zero_crossing_pin: GPIO23
          regulator_zero_cross_inverted: false
          
      - path: solar_router/engine_1dimmer.yaml
        vars:
          green_led_pin: GPIO19
          yellow_led_pin: GPIO18

      # ajout des capteurs pour le debug
      - path: solar_router/debug_sensors.yaml
