esphome:
  name: solarrouter-jsy
  friendly_name: SolarRouter
  min_version: 2025.9.0
  name_add_mac_suffix: false

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
  level: DEBUG
  logs:
    # Masque les logs détaillés du Modbus (requêtes/réponses)
    modbus: ERROR
    modbus_controller: ERROR
    modbus_controller.sensor: ERROR
#      sensor: ERROR

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
  - platform: esphome
  - platform: web_server

web_server:
  port: 80

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# ----------------------------------------------------------------------------------------------------
# Customisation
# ----------------------------------------------------------------------------------------------------
packages:
  solar_router:
    url: https://github.com/hacf-fr/Solar-Router-for-ESPHome/
    ref: main
    refresh: 1d
    files:
      - path: solar_router/common.yaml

      # Manage JSY-MK-194T
      - path: solar_router/jsy-mk-194t_common.yaml
        vars:
          uart_tx_pin: GPIO26
          uart_rx_pin: GPIO27
          uart_baud_rate: 4800
          AP_Ch2_internal: "false"

      # Read diverted energy with JSY-MK-194T
      - path: solar_router/energy_counter_jsy-mk-194t.yaml

      # In automatic mode, measuring power exchanged with the grid via JSY-MK-194T
      - path: solar_router/power_meter_jsy-mk-194t.yaml
        vars:
          consumption_sensor_internal: true # Prevents the “Consumption” sensor from being displayed in Home Assistant, as it is never used and remains “unavailable” when using the JSY-MK-194T

      - path: solar_router/regulator_triac.yaml
        vars:
          regulator_gate_pin: GPIO22
          regulator_zero_crossing_pin: GPIO23
          regulator_zero_cross_inverted: false

      - path: solar_router/engine_1dimmer.yaml
        vars:
          green_led_pin: GPIO19
          yellow_led_pin: GPIO18

      # Add debug sensirs
      - path: solar_router/debug_sensors.yaml
