# ----------------------------------------------------------------------------------------------------
# Calculate daily energy diverted with JSY-MK-194T
# ----------------------------------------------------------------------------------------------------
esphome:
  includes:
    - solar_router/lambda/jsy-mk-194t_common.h

sensor:
  # Sensor showing the total daily energy diverted consumption
  - id: energy_diverted
    platform: total_daily_energy
    name: "Total daily energy diverted"
    power_id: power_divertion
    unit_of_measurement: "kWh"
    state_class: total_increasing
    device_class: energy
    accuracy_decimals: 3
    filters:
      # Multiplication factor from W to kW is 0.001
      - multiply: 0.001

  - platform: template
    name: Power divertion
    id: power_divertion
    unit_of_measurement: "W"
    device_class: power

# Script updating the power consumed counter
script:
  - id: energy_diverted_counter
    mode: single
    then:
      - lambda: |-
          jsy_mk_194t::energy_diverted_counter();

# Enable time component to
#  - Update energy diverted counter
#  - Reset energy at midnight
time:
  - platform: sntp
    on_time:
      # Executed every second → energy diverted
      - seconds: /1
        then:
          - script.execute: energy_diverted_counter
