substitutions:
  U_Ch1_internal: "true"
  I_Ch1_internal: "true"
  AP_Ch1_internal: "true"
  PAE_Ch1_internal: "true"
  PF_Ch1_internal: "true"
  NAE_Ch1_internal: "true"
  PD_Ch1_internal: "true"
  PD_Ch2_internal: "true"
  frequency_internal: "true"
  U_Ch2_internal: "true"
  I_Ch2_internal: "true"
  AP_Ch2_internal: "true"
  PAE_Ch2_internal: "true"
  PF_Ch2_internal: "true"
  NAE_Ch2_internal: "true"

<<: !include power_meter_common.yaml

# Configuration UART pour le JSY-MK-194T
uart:
  id: uart_bus
  tx_pin: ${uart_tx_pin}
  rx_pin: ${uart_rx_pin}
  baud_rate: ${uart_baud_rate}
  parity: NONE
  stop_bits: 1

modbus:
#flow_control_pin: 5
  #send_wait_time: 200ms
  id: modbus1

modbus_controller:
  - id: jsymk
    ## the Modbus device addr
    address: 0x1
    modbus_id: modbus1
    update_interval: 0.75s
    command_throttle: 50ms
    # setup_priority: -10

sensor:  

# tension de l'alimentation
  - platform: modbus_controller
    modbus_controller_id: jsymk
    id: U_Ch1
    name: "Voltage Ch1"
    address: 0x0048
    unit_of_measurement: "V"
    register_type: holding
    value_type: U_DWORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.0001
    register_count: 1
    response_size: 4
    internal: ${U_Ch1_internal}

# Intensité traversant le tore
  - platform: modbus_controller
    modbus_controller_id: jsymk
    id: I_Ch1
    name: "Current Ch1"
    address: 0x0049
    unit_of_measurement: "A"
    register_type: holding
    value_type: U_DWORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.0001
    register_count: 1
    response_size: 4
    state_class: measurement
    internal: ${I_Ch1_internal}

# Puissance traversant le tore
  - platform: modbus_controller
    modbus_controller_id: jsymk
    id: AP_Ch1
    name: "Active Power Ch1"
    address: 0x004A
    unit_of_measurement: "W"
    register_type: holding
    value_type: U_DWORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.0001
    register_count: 1
    response_size: 4
    state_class: measurement
    internal: ${AP_Ch1_internal}

# Energie active positive lue dans le tore
  - platform: modbus_controller
    modbus_controller_id: jsymk
    id: PAE_Ch1
    name: "Positive Active Energy Ch1"
    address: 0x004B
    unit_of_measurement: "kWh"
    register_type: holding
    value_type: U_DWORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.0001
    register_count: 1
    response_size: 4
    state_class: total
    internal: ${PAE_Ch1_internal}

# Facteur de forme CH1
  - platform: modbus_controller
    modbus_controller_id: jsymk
    id: PF_Ch1
    name: "Power Factor Ch1"
    address: 0x004C
    register_type: holding
    value_type: U_DWORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.001
    register_count: 1
    response_size: 4
    internal: ${PF_Ch1_internal}

# Energie NEG lue CH1
  - platform: modbus_controller
    modbus_controller_id: jsymk
    id: NAE_Ch1
    name: "Negative Active Energy Ch1"
    address: 0x004D
    unit_of_measurement: "kWh"
    register_type: holding
    value_type: U_DWORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.0001     
    register_count: 1
    response_size: 4 
    state_class: total
    internal: ${NAE_Ch1_internal}
    
# Direction de la puissance dans CH1
  - platform: modbus_controller
    modbus_controller_id: jsymk
    id: PD_Ch1
    name: "Power Direction Ch1"
    address: 0x004E
    register_type: holding
    value_type: U_DWORD
    bitmask: 0X00010000
    filters:
      - multiply: 1
    register_count: 1
    response_size: 4
    internal: ${PD_Ch1_internal}

# Direction de la puissance dans CH2
  - platform: modbus_controller
    modbus_controller_id: jsymk
    id: PD_Ch2
    name: "Power Direction Ch2"
    address: 0x004E
    register_type: holding
    value_type: U_DWORD
    accuracy_decimals: 0
    bitmask: 0X01000000
    filters:
      - multiply: 1
    register_count: 1
    response_size: 4
    internal: ${PD_Ch2_internal}

# Fréquence réseau 
  - platform: modbus_controller
    modbus_controller_id: jsymk
    id: frequency
    name: "Frequency"
    address: 0x004F
    unit_of_measurement: "hz"    
    register_type: holding
    value_type: U_DWORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.01
    register_count: 1
    response_size: 4
    internal: ${frequency_internal}

# tension de l'alimentation => pas d'interet car U_Ch1 = U_Ch2 (une seule mesure)
#  - platform: modbus_controller
#    modbus_controller_id: jsymk
#    id: U_Ch2
#    name: "Voltage Ch2"
#    address: 0x0050
#    unit_of_measurement: "V"
#    register_type: holding
#    value_type: U_DWORD
#    accuracy_decimals: 1
#    filters:
#      - multiply: 0.0001
#    register_count: 1
#    response_size: 4
#    internal: ${U_Ch2_internal}
    
# Intensité lue dans la pince
  - platform: modbus_controller
    modbus_controller_id: jsymk
    id: I_Ch2
    name: "Current Ch2"
    address: 0x0051
    unit_of_measurement: "A"
    register_type: holding
    value_type: U_DWORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.0001
    register_count: 1
    response_size: 4
    internal: ${I_Ch2_internal}

# puissance lue dans la pince
  - platform: modbus_controller
    modbus_controller_id: jsymk
    id: AP_Ch2
    name: "Active Power Ch2"
    address: 0x0052
    unit_of_measurement: "W"
    register_type: holding
    value_type: U_DWORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.0001
    register_count: 1
    response_size: 4 
    internal: ${AP_Ch2_internal}
    on_value:
      then:
        - lambda: |-
            if ( id(PD_Ch2).state == 1 ) {
              id(pureseau1).publish_state( id(AP_Ch2).state *-1);
            } else {
              id(pureseau1).publish_state( id(AP_Ch2).state );
            }
    
# Energie lue dans la pince
  - platform: modbus_controller
    modbus_controller_id: jsymk
    id: PAE_Ch2
    name: "Positive Active Energy Ch2"
    address: 0x0053
    unit_of_measurement: "kWh"
    register_type: holding
    value_type: U_DWORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.0001
    register_count: 1
    response_size: 4
    internal: ${PAE_Ch2_internal}

# Energie lue dans le tore
  - platform: modbus_controller
    modbus_controller_id: jsymk
    id: PF_Ch2
    name: "Power Factor Ch2"
    address: 0x0054
    register_type: holding
    value_type: U_DWORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.001
    register_count: 1
    response_size: 4
    internal: ${PF_Ch2_internal}

# Energie NEG lue dans le tore
  - platform: modbus_controller
    modbus_controller_id: jsymk
    id: NAE_Ch2
    name: "Negative Active Energy Ch2"
    address: 0x0055
    unit_of_measurement: "kWh"
    register_type: holding
    value_type: U_DWORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.0001     
    register_count: 1
    response_size: 4 
    internal: ${NAE_Ch2_internal}
    
# Affichage dans HA et sur l'afficheur
  - platform: template
    name: "Pu Reseau"
    id: pureseau1
    unit_of_measurement: "W"
    state_class: "measurement"  

# ----------------------------------------------------------------------------------------------------
# Calculate daily energy diverted
# ----------------------------------------------------------------------------------------------------

# Sensor showing the actual energy diverted consumption
  - id: energy_diverted
    platform: total_daily_energy
    name: 'Total energy diverted'
    power_id: power_divertion
    unit_of_measurement: 'kWh'
    state_class: total_increasing
    device_class: energy
    accuracy_decimals: 3
    filters:
      # Multiplication factor from W to kW is 0.001
      - multiply: 0.001

  - platform: template
    name: Power divertion
    id: power_divertion
    unit_of_measurement: 'W'
    
# Define the power of load plugged on the solar router
number:
  - platform: template
    name: "Load power"
    id: load_power
    min_value: 0
    max_value: 99999
    step: 1
    unit_of_measurement: "W"
    optimistic: True
    restore_value: true
    
# Script updating the power consumed counter
script:
  - id: power_meter_source
    mode: single
    then:
      - lambda: |-
          // Récupère la dernière valeur du capteur Modbus
          float value = id(AP_Ch1).state;

          // Vérifie si la valeur est valide
          if (!isnan(value)) {
            id(consumption).publish_state(value);
          } else {
            id(consumption).publish_state(NAN);
          }

  - id: energy_diverted_counter
    mode: single
    then:
      - lambda: |-
          // Ensure that consumption is a valid float
          float consumption_state = id(consumption).state;  // Access the state of the consumption sensor
          
          // Check if consumption is greater than AP_Ch1 or is unknown
          if (consumption_state >= id(AP_Ch1).state || isnan(consumption_state))  // Access the state of AP_Ch1 if it's a sensor
          {
              // Power diverted is consumed (or we don't know the consumption)
              id(power_divertion).publish_state(id(AP_Ch1).state);  // Use the state of AP_Ch1
          }
          else
          {
              // Power diverted is not consumed
              id(power_divertion).publish_state(0.0);  // Make sure this is a float value
          }



# Enable time component to 
#  - Update energy diverted counter
#  - Reset energy at midnight
time:
  - platform: homeassistant
    id: homeassistant_time_for_solar_router

  - platform: sntp
    on_time:
      # Exécuté chaque seconde → energy diverted
      - seconds: /1
        then:
          - script.execute: energy_diverted_counter

      # Exécuté chaque seconde → power meter source (si activé)
      - seconds: /1
        then:
          - if:
              condition:
                lambda: return id(power_meter_activated) != 0;
              then:
                - script.execute: power_meter_source
