# ----------------------------------------------------------------------------------------------------
# User interaction
# ----------------------------------------------------------------------------------------------------

substitutions:
  U_Ch1_internal: "true"
  I_Ch1_internal: "true"
  AP_Ch1_internal: "true"
  PAE_Ch1_internal: "true"
  PF_Ch1_internal: "true"
  NAE_Ch1_internal: "true"
  PD_Ch1_internal: "true"
  PD_Ch2_internal: "true"
  frequency_internal: "true"
  U_Ch2_internal: "true"
  I_Ch2_internal: "true"
  AP_Ch2_internal: "true"
  PAE_Ch2_internal: "true"
  PF_Ch2_internal: "true"
  NAE_Ch2_internal: "true"

# Configuration UART pour le JSY-MK-194T
uart:
  id: uart_bus
  tx_pin: ${uart_tx_pin}
  rx_pin: ${uart_rx_pin}
  baud_rate: ${uart_baud_rate}
  parity: NONE
  stop_bits: 1

modbus:
#flow_control_pin: 5
  #send_wait_time: 200ms
  id: modbus1

modbus_controller:
  - id: jsymk
    ## the Modbus device addr
    address: 0x1
    modbus_id: modbus1
    update_interval: 2s
    command_throttle: 100ms
    # setup_priority: -10

sensor:  
# tension de l'alimentation
  - platform: modbus_controller
    modbus_controller_id: jsymk
    id: U_Ch1
    name: "Voltage Ch1"
    address: 0x0048
    unit_of_measurement: "V"
    device_class: voltage
    state_class: measurement
    register_type: holding
    value_type: U_DWORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.0001
    register_count: 1
    response_size: 4
    internal: ${U_Ch1_internal}

# Intensité traversant le tore
  - platform: modbus_controller
    modbus_controller_id: jsymk
    id: I_Ch1
    name: "Current Ch1"
    address: 0x0049
    unit_of_measurement: "A"
    device_class: current
    register_type: holding
    value_type: U_DWORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.0001
    register_count: 1
    response_size: 4
    state_class: measurement
    internal: ${I_Ch1_internal}

# Puissance traversant le tore
  - platform: modbus_controller
    modbus_controller_id: jsymk
    id: AP_Ch1
    name: "Active Power Ch1"
    address: 0x004A
    unit_of_measurement: "W"
    device_class: "power"
    register_type: holding
    value_type: U_DWORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.0001
    register_count: 1
    response_size: 4
    state_class: measurement
    internal: ${AP_Ch1_internal}

# Energie active positive lue dans le tore
  - platform: modbus_controller
    modbus_controller_id: jsymk
    id: PAE_Ch1
    name: "Positive Active Energy Ch1"
    address: 0x004B
    unit_of_measurement: "kWh"
    device_class: energy
    register_type: holding
    value_type: U_DWORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.0001
    register_count: 1
    response_size: 4
    state_class: total
    internal: ${PAE_Ch1_internal}

# Facteur de forme CH1
  - platform: modbus_controller
    modbus_controller_id: jsymk
    id: PF_Ch1
    name: "Power Factor Ch1"
    address: 0x004C
    unit_of_measurement: "%"
    device_class: power factor
    register_type: holding
    value_type: U_DWORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.001
    register_count: 1
    response_size: 4
    internal: ${PF_Ch1_internal}

# Energie NEG lue CH1
  - platform: modbus_controller
    modbus_controller_id: jsymk
    id: NAE_Ch1
    name: "Negative Active Energy Ch1"
    address: 0x004D
    unit_of_measurement: "kWh"
    device_class: energy
    register_type: holding
    value_type: U_DWORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.0001     
    register_count: 1
    response_size: 4 
    state_class: total
    internal: ${NAE_Ch1_internal}
    
# Direction de la puissance dans CH1
  - platform: modbus_controller
    modbus_controller_id: jsymk
    id: PD_Ch1
    name: "Power Direction Ch1"
    address: 0x004E
    register_type: holding
    value_type: U_DWORD
    bitmask: 0X00010000
    filters:
      - multiply: 1
    register_count: 1
    response_size: 4
    internal: ${PD_Ch1_internal}

# Direction de la puissance dans CH2
  - platform: modbus_controller
    modbus_controller_id: jsymk
    id: PD_Ch2
    name: "Power Direction Ch2"
    address: 0x004E
    register_type: holding
    value_type: U_DWORD
    accuracy_decimals: 0
    bitmask: 0X01000000
    filters:
      - multiply: 1
    register_count: 1
    response_size: 4
    internal: ${PD_Ch2_internal}

# Fréquence réseau 
  - platform: modbus_controller
    modbus_controller_id: jsymk
    id: frequency
    name: "Frequency"
    address: 0x004F
    unit_of_measurement: "Hz"    
    device_class: frequency
    register_type: holding
    value_type: U_DWORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.01
    register_count: 1
    response_size: 4
    internal: ${frequency_internal}

# tension de l'alimentation => pas d'interet car U_Ch1 = U_Ch2 (une seule mesure)
#  - platform: modbus_controller
#    modbus_controller_id: jsymk
#    id: U_Ch2
#    name: "Voltage Ch2"
#    address: 0x0050
#    unit_of_measurement: "V"
#    device_class: voltage
#    register_type: holding
#    value_type: U_DWORD
#    accuracy_decimals: 1
#    filters:
#      - multiply: 0.0001
#    register_count: 1
#    response_size: 4
#    internal: ${U_Ch2_internal}
    
# Intensité lue dans la pince
  - platform: modbus_controller
    modbus_controller_id: jsymk
    id: I_Ch2
    name: "Current Ch2"
    address: 0x0051
    unit_of_measurement: "A"
    device_class: current
    register_type: holding
    value_type: U_DWORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.0001
    register_count: 1
    response_size: 4
    internal: ${I_Ch2_internal}

# puissance lue dans la pince
  - platform: modbus_controller
    modbus_controller_id: jsymk
    id: AP_Ch2
    name: "Active Power Ch2"
    address: 0x0052
    unit_of_measurement: "W"
    device_class: power
    register_type: holding
    value_type: U_DWORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.0001
    register_count: 1
    response_size: 4 
    internal: ${AP_Ch2_internal}
#    on_value:
#      then:
#        - lambda: |-
#            if ( id(PD_Ch2).state == 1 ) {
#              id(pureseau1).publish_state( id(AP_Ch2).state *-1);
#            } else {
#              id(pureseau1).publish_state( id(AP_Ch2).state );
#            }
    
# Energie lue dans la pince
  - platform: modbus_controller
    modbus_controller_id: jsymk
    id: PAE_Ch2
    name: "Positive Active Energy Ch2"
    address: 0x0053
    unit_of_measurement: "kWh"    
    device_class: energy
    register_type: holding
    value_type: U_DWORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.0001
    register_count: 1
    response_size: 4
    internal: ${PAE_Ch2_internal}

# Energie lue dans le tore
  - platform: modbus_controller
    modbus_controller_id: jsymk
    id: PF_Ch2
    name: "Power Factor Ch2"
    unit_of_measurement: "%"
    device_class: power factor
    address: 0x0054
    register_type: holding
    value_type: U_DWORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.001
    register_count: 1
    response_size: 4
    internal: ${PF_Ch2_internal}

# Energie NEG lue dans le tore
  - platform: modbus_controller
    modbus_controller_id: jsymk
    id: NAE_Ch2
    name: "Negative Active Energy Ch2"
    address: 0x0055
    unit_of_measurement: "kWh"
    device_class: energy
    register_type: holding
    value_type: U_DWORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.0001     
    register_count: 1
    response_size: 4 
    internal: ${NAE_Ch2_internal}
