# ----------------------------------------------------------------------------------------------------
# User interaction
# ----------------------------------------------------------------------------------------------------

substitutions:
  power_meter_activated_at_start: "0"  
  real_power_optional: ""

# Activate or not power meter
globals:
  - id: power_meter_activated
    type: int
    initial_value: ${power_meter_activated_at_start}
    restore_value: True


