# ----------------------------------------------------------------------------------------------------
# User interaction
# ----------------------------------------------------------------------------------------------------

# Activate or not power meter
globals:
    - id: power_meter_activated
      type: int
      initial_value: ${power_meter_activated_at_start}
      restore_value: True

# ----------------------------------------------------------------------------------------------------
# Calculate daily energy diverted
# ----------------------------------------------------------------------------------------------------

sensor:  

  # Sensor showing the actual power consumption
  - id: real_power
    platform: template
    name: "Real Power"
    device_class: "power"
    unit_of_measurement: "W"
    update_interval: 1s
    
  # Sensor showing the actual power consumption
  - id: consumption
    platform: template
    name: "Consumption"
    device_class: "power"
    unit_of_measurement: "W"
    update_interval: 1s
    internal: true
    
    
# Script updating the power consumed counter
script:
  - id: power_meter_source
    mode: single
    then:
      - logger.log: "************************************************************"
      - lambda: |-
          // Récupère la dernière valeur du capteur Modbus
          float value = id(AP_Ch2).state;

          // Vérifie si la valeur est valide
          if (!isnan(value)) {
            id(real_power).publish_state(value);
          } else {
            id(real_power).publish_state(NAN);
          }



# Enable time component to 
#  - Update energy diverted counter
#  - Reset energy at midnight
time:
  - platform: homeassistant
    id: homeassistant_time_for_solar_router

  - platform: sntp
    on_time:
      # Exécuté chaque seconde → energy diverted
      - seconds: /1
        then:
          - if:
              condition:
                lambda: return id(power_meter_activated) != 0;
              then:
                - script.execute: power_meter_source
