<<: !include power_meter_common.yaml

esphome:
  includes:
    - solar_router/jsy-mk-194t_common.h

# Script updating the actual power exchange
script:
  # Get power reports from JSY-MK-194T and update globals (real_power)
  # Power exchanged with the grid is names "Value"
  - id: power_meter_source
    mode: single
    then:
      - lambda: |-
          jsy_mk_194t::read_real_power(${power_sign});

time:
  - platform: sntp
    on_time:
      - seconds: /1
        then:
          - if:
              condition:
                lambda: return id(power_meter_activated) != 0;
              then:
                - script.execute: power_meter_source
