<<: !include power_meter_common.yaml

esphome:
  min_version: 2024.11.1
  includes:
    - solar_router/lambda/power_meter_proxy_client.h

# ----------------------------------------------------------------------------------------------------
# Use http request component
# ----------------------------------------------------------------------------------------------------

http_request:
  id: http_request_data
  useragent: esphome/device
  timeout: 10s
  verify_ssl: False

# ----------------------------------------------------------------------------------------------------
# Define scripts for power collection
# ----------------------------------------------------------------------------------------------------

script:
  # Get power reports from another PowerMEter and update globals (real_power)
  # Information are provided as json. Power exchanged with the grid is names "Value"
  - id: power_meter_source
    mode: single
    then:
      - if:
          condition:
            lambda: "return network::is_connected();"
          then:
            - http_request.get:
                url: http://${power_meter_ip_address}/sensor/real_power
                capture_response: true
                max_response_buffer_size: 4096
                on_response:
                  then:
                    - lambda: |-
                        proxy_client::power_meter_source_real_power_on_response(response->status_code, body);
                on_error:
                  then:
                    - lambda: |-
                        proxy_client::power_meter_source_real_power_on_error();
            - http_request.get:
                url: http://${power_meter_ip_address}/sensor/consumption
                capture_response: true
                max_response_buffer_size: 4096
                on_response:
                  then:
                    - lambda: |-
                        proxy_client::power_meter_source_consumption_on_response(response->status_code, body);
                on_error:
                  then:
                    - lambda: |-
                        proxy_client::power_meter_source_consumption_on_error();
time:
  - platform: sntp
    on_time:
      - seconds: /1
        then:
          - if:
              condition:
                - lambda: return id(power_meter_activated) != 0;
              then:
                - script.execute: power_meter_source
