<<: !include power_meter_common.yaml

esphome:
  min_version: 2025.5.0

# ----------------------------------------------------------------------------------------------------
# HTTP client
# ----------------------------------------------------------------------------------------------------
http_request:
  id: http_request_data
  useragent: esphome/device
  timeout: 10s
  verify_ssl: false

# ----------------------------------------------------------------------------------------------------
# Power meter script (Shelly EM Pro)
# ----------------------------------------------------------------------------------------------------
script:
  - id: power_meter_source
    mode: single
    then:
      - if:
          condition:
            lambda: return network::is_connected();
          then:
            - http_request.get:
                url: http://${power_meter_ip_address}/rpc/Shelly.GetStatus
                request_headers:
                  Content-Type: application/json
                  Authorization: ${power_meter_auth_header}
                capture_response: true
                max_response_buffer_size: 4096

                on_response:
                  then:
                    - logger.log:
                        format: "Shelly HTTP %d (%u ms)"
                        args:
                          - response->status_code
                          - response->duration_ms

                    - lambda: |-
                        if (response->status_code != 200) {
                          ESP_LOGW("shelly", "HTTP error %d", response->status_code);
                          id(real_power).publish_state(NAN);
                          return;
                        }

                        bool ok = json::parse_json(body, [&](JsonObject root) -> bool {
                          int index = ${emeter_index};
                          String key = "em1:" + String(index);

                          if (!root[key.c_str()]["act_power"].is<float>()) {
                            ESP_LOGW("shelly", "act_power not found for %s", key.c_str());
                            return false;
                          }

                          float power = root[key.c_str()]["act_power"].as<float>();
                          id(real_power).publish_state(power);
                          return true;
                        });

                        if (!ok) {
                          ESP_LOGW("shelly", "JSON parse failed");
                          id(real_power).publish_state(NAN);
                        }

                on_error:
                  then:
                    - lambda: |-
                        ESP_LOGW("shelly", "HTTP request failed");
                        id(real_power).publish_state(NAN)

# ----------------------------------------------------------------------------------------------------
# Periodic update
# ----------------------------------------------------------------------------------------------------
time:
  - platform: sntp
    on_time:
      - seconds: /1
        then:
          - if:
              condition:
                lambda: return id(power_meter_activated) != 0;
              then:
                - script.execute: power_meter_source
