<<: !include power_meter_common.yaml

esphome:
  min_version: 2025.5.0
  includes:
    - solar_router/power_meter_fronius.h

# ----------------------------------------------------------------------------------------------------
# Use http request component
# ----------------------------------------------------------------------------------------------------

http_request:
  id: http_request_data
  useragent: esphome/device
  timeout: 10s
  verify_ssl: False

# ----------------------------------------------------------------------------------------------------
# Define scripts for power collection
# ----------------------------------------------------------------------------------------------------

script:
  # Fronius script gather power reports from inverter and update globals (real_power)
  # Information are provided as json. Power exchanged with the grid is names PowerReal_P_Sum
  # When this value is positive, energy is taken from the grid.
  # When this value is negative, energy is pushed to the grid.
  - id: power_meter_source
    mode: single
    then:
      - if:
          condition:
            lambda: "return network::is_connected();"
          then:
            - http_request.get:
                url: http://${power_meter_ip_address}/solar_api/v1/GetMeterRealtimeData.cgi
                request_headers:
                  Content-Type: application/json
                capture_response: true
                max_response_buffer_size: 4096
                on_response:
                  then:
                    - lambda: |-
                        fronius::real_power_on_response(response->status_code, body);
                on_error:
                  then:
                    - lambda: |-
                        fronius::real_power_on_error();
            - http_request.get:
                url: http://${power_meter_ip_address}/solar_api/v1/GetPowerFlowRealtimeData.fcgi
                request_headers:
                  Content-Type: application/json
                capture_response: true
                max_response_buffer_size: 4096
                on_response:
                  then:
                    - lambda: |-
                        fronius::consumption_on_response(response->status_code, body);
                on_error:
                  then:
                    - lambda: |-
                        fronius::consumption_on_error();
time:
  - platform: sntp
    on_time:
      - seconds: /1
        then:
          - if:
              condition:
                - lambda: return id(power_meter_activated) != 0;
              then:
                - script.execute: power_meter_source
