# Differences vs original scheduler:
# - Forced scheduler is blocked during the day if temperature is reached
# - Night forced run only happens if water was NOT hot enough during the day
# - Safety_limit immediately stops forced run
# - No C++ calls, ESPHome-safe logic only

substitutions:
  scheduler_unique_id: "Forced"
  custom_script: ${scheduler_unique_id}_fake_script

globals:
  # Memorize if temperature was reached during the day
  - id: day_temperature_reached
    type: bool
    restore_value: true
    initial_value: "false"

script:
  # Dummy script
  - id: ${scheduler_unique_id}_fake_script
    then:

  # Central autonomy logic
  - id: ${scheduler_unique_id}_auto_manager
    mode: restart
    then:
      - lambda: |-
          auto now = id(${scheduler_unique_id}_sntp).now();
          if (!now.is_valid()) return;

          int minutes = now.hour * 60 + now.minute;
          bool is_day = (minutes >= 8 * 60) && (minutes < 19 * 60);

          ESP_LOGI("scheduler",
            "Temp=%.1f Safety=%d Day=%d DayReached=%d",
            id(safety_temperature).state,
            id(safety_limit),
            is_day,
            id(day_temperature_reached)
          );

          // Temperature reached at any moment
          if (id(safety_limit)) {
            id(${scheduler_unique_id}_scheduler_activate).turn_off();
            id(day_temperature_reached) = is_day ? true : id(day_temperature_reached);
            return;
          }

          // Daytime: never allow forced scheduler
          if (is_day) {
            id(${scheduler_unique_id}_scheduler_activate).turn_off();
            return;
          }

          // Night: allow forced scheduler ONLY if water was NOT hot during the day
          if (!id(day_temperature_reached)) {
            id(${scheduler_unique_id}_scheduler_activate).turn_on();
          } else {
            id(${scheduler_unique_id}_scheduler_activate).turn_off();
          }

switch:
  - platform: template
    name: "Activate ${scheduler_unique_id} Scheduler"
    optimistic: true
    restore_mode: RESTORE_DEFAULT_OFF
    id: "${scheduler_unique_id}_scheduler_activate"
    on_turn_off:
      then:
        - number.set:
            id: router_level
            value: 0
        - switch.turn_on: activate

number:
  - platform: template
    name: "${scheduler_unique_id} Scheduler Router Level"
    id: "${scheduler_unique_id}_scheduler_router_level"
    min_value: 0
    max_value: 100
    initial_value: 100
    step: 1
    optimistic: true
    mode: slider

time:
  - platform: sntp
    id: ${scheduler_unique_id}_sntp
    on_time:
      - seconds: 0
        minutes: /5
        then:
          - script.execute: ${scheduler_unique_id}_auto_manager

esphome:
  on_boot:
    priority: -1000
    then:
      - script.execute: ${scheduler_unique_id}_auto_manager
