# Stop Forced Scheduler when temperature is above stop_temperature
# or when Safety limit reached is active
# Track if temperature was reached during the day (08h–19h)
# Variable is persistent and reset every day at 08:00
# Auto-activate Forced Scheduler when heating is really needed

substitutions:
  scheduler_unique_id: "Forced"
  custom_script: ${scheduler_unique_id}_fake_script

script:
  # A fake empty script to run if user don't provide a custom one
  - id: ${scheduler_unique_id}_fake_script
    then:

  # === DAY TEMPERATURE TRACKING ===
  - id: ${scheduler_unique_id}_day_temperature_tracker
    mode: single
    then:
      - lambda: |-
          auto now = id(${scheduler_unique_id}_sntp).now();
          if (!now.is_valid()) return;

          int now_min = now.hour * 60 + now.minute;
          if (now_min < 8 * 60 || now_min >= 19 * 60) return;

          if (
            !isnan(id(safety_temperature).state) &&
            id(safety_temperature).state >= id(stop_temperature).state
          ) {
            if (!id(temperature_atteinte_60).state) {
              ESP_LOGI("forced_scheduler", "Day temperature reached");
              id(temperature_atteinte_60).turn_on();
            }
          }

  # === SAFETY / TEMPERATURE GUARD ===
  - id: ${scheduler_unique_id}_temperature_guard
    mode: single
    then:
      - lambda: |-
          auto now = id(${scheduler_unique_id}_sntp).now();
          if (!now.is_valid()) return;

          int now_min = now.hour * 60 + now.minute;
          int begin_min =
            id(${scheduler_unique_id}_scheduler_begin_hour).state * 60 +
            id(${scheduler_unique_id}_scheduler_begin_min).state;
          int end_min =
            id(${scheduler_unique_id}_scheduler_end_hour).state * 60 +
            id(${scheduler_unique_id}_scheduler_end_min).state;

          bool in_window =
            (begin_min <= end_min)
              ? (now_min >= begin_min && now_min < end_min)
              : (now_min >= begin_min || now_min < end_min);

          if (!in_window) return;

          if (
            id(safety_limit) ||
            (!isnan(id(safety_temperature).state) &&
             id(safety_temperature).state >= id(stop_temperature).state)
          ) {
            ESP_LOGW("forced_scheduler", "STOP Forced Scheduler");
            id(${scheduler_unique_id}_scheduler_activate).turn_off();
          }

  # === AUTO MANAGER (🔥 MISSING PIECE) ===
  - id: ${scheduler_unique_id}_auto_manager
    mode: single
    then:
      - lambda: |-
          auto now = id(${scheduler_unique_id}_sntp).now();
          if (!now.is_valid()) return;

          int now_min = now.hour * 60 + now.minute;
          int begin_min =
            id(${scheduler_unique_id}_scheduler_begin_hour).state * 60 +
            id(${scheduler_unique_id}_scheduler_begin_min).state;
          int end_min =
            id(${scheduler_unique_id}_scheduler_end_hour).state * 60 +
            id(${scheduler_unique_id}_scheduler_end_min).state;

          bool in_window =
            (begin_min <= end_min)
              ? (now_min >= begin_min && now_min < end_min)
              : (now_min >= begin_min || now_min < end_min);

          if (!in_window) return;

          if (
            !id(safety_limit) &&
            !id(temperature_atteinte_60).state &&
            !isnan(id(safety_temperature).state) &&
            id(safety_temperature).state < id(stop_temperature).state
          ) {
            if (!id(${scheduler_unique_id}_scheduler_activate).state) {
              ESP_LOGI("forced_scheduler", "AUTO → Activate Forced Scheduler");
              id(${scheduler_unique_id}_scheduler_activate).turn_on();
            }
          }

switch:
  - platform: template
    name: "Temp atteinte dans la journée"
    id: temperature_atteinte_60
    optimistic: true
    restore_mode: RESTORE_DEFAULT_OFF

  - platform: template
    name: "Activate ${scheduler_unique_id} Scheduler"
    optimistic: true
    restore_mode: RESTORE_DEFAULT_ON
    id: "${scheduler_unique_id}_scheduler_activate"
    on_turn_off:
      then:
        - if:
            condition:
              - switch.is_off: activate
            then:
              - number.set:
                  id: router_level
                  value: 0
              - switch.turn_on: activate

number:
  - platform: template
    name: "${scheduler_unique_id} Scheduler Router Level"
    id: "${scheduler_unique_id}_scheduler_router_level"
    min_value: 0
    max_value: 100
    initial_value: 100
    step: 1
    unit_of_measurement: "%"
    optimistic: true
    mode: slider

  - platform: template
    name: "${scheduler_unique_id} Scheduler Checking End Threshold"
    id: "${scheduler_unique_id}_scheduler_checking_end_threshold"
    optimistic: true
    min_value: 0
    max_value: 720
    step: 5
    mode: box
    initial_value: 5

  - platform: template
    name: "${scheduler_unique_id} Scheduler Begin Minute"
    id: "${scheduler_unique_id}_scheduler_begin_min"
    optimistic: true
    min_value: 0
    max_value: 55
    step: 5
    mode: box
    initial_value: 0

  - platform: template
    name: "${scheduler_unique_id} Scheduler End Minute"
    id: "${scheduler_unique_id}_scheduler_end_min"
    optimistic: true
    min_value: 0
    max_value: 55
    step: 5
    mode: box
    initial_value: 0

  - platform: template
    name: "${scheduler_unique_id} Scheduler Begin Hour"
    id: "${scheduler_unique_id}_scheduler_begin_hour"
    optimistic: true
    min_value: 0
    max_value: 23
    step: 1
    mode: box
    initial_value: 22

  - platform: template
    name: "${scheduler_unique_id} Scheduler End Hour"
    id: "${scheduler_unique_id}_scheduler_end_hour"
    optimistic: true
    min_value: 0
    max_value: 23
    step: 1
    mode: box
    initial_value: 6

time:
  - platform: sntp
    id: ${scheduler_unique_id}_sntp
    on_time:
      # Reset daily flag at 08:00
      - hours: 8
        minutes: 0
        seconds: 0
        then:
          - switch.turn_off: temperature_atteinte_60

      # At 19:00 → decision for the night
      - hours: 19
        minutes: 0
        seconds: 0
        then:
          - script.execute: ${scheduler_unique_id}_auto_manager

      # Every minute
      - seconds: 0
        minutes: /1
        then:
          - script.execute: ${scheduler_unique_id}_day_temperature_tracker
          - script.execute: ${scheduler_unique_id}_temperature_guard
          - script.execute: ${scheduler_unique_id}_auto_manager

esphome:
  on_boot:
    priority: -100
    then:
      - script.execute: ${scheduler_unique_id}_auto_manager
