# If temperature is higher than stop_temperature,
#    then safety_limit is set to True
# It safety_limit is True and temperature is smaller the restart_temperature,
#    then safety_limit is set to False
# ... or the opposit if you want to use it for a cooling system
esphome:
  on_boot:
    priority: -1000.0
    then:
      - script.execute: safety_limit_check
  includes:
    - solar_router/lambda/temperature_limiter_common.h

globals:
  - id: used_for_cooling
    type: bool
    initial_value: "false"

number:
  - platform: template
    id: stop_temperature
    name: "Stop temperature"
    max_value: 99999
    initial_value: 50
    min_value: -273
    step: 1
    optimistic: True
    mode: box
    unit_of_measurement: "°C"
    restore_value: true

  - platform: template
    id: restart_temperature
    name: "Restart temperature"
    max_value: 99999
    initial_value: 40
    min_value: -273
    step: 1
    optimistic: True
    mode: box
    unit_of_measurement: "°C"
    restore_value: true

# Safety limit binary sensor representing safety_limit from engine
binary_sensor:
  - platform: template
    name: "Safety limit reached"
    lambda: return id(safety_limit);

switch:
  - platform: template
    name: "Used for cooling"
    optimistic: True
    on_turn_on:
      then:
        - globals.set:
            id: used_for_cooling
            value: "true"
    on_turn_off:
      then:
        - globals.set:
            id: used_for_cooling
            value: "false"

script:
  - id: safety_limit_check
    mode: single
    then:
      - lambda: |-
          temperature_limiter_common::safety_limit_check();

output:
  - id: red_led
    platform: gpio
    pin:
      number: ${red_led_pin}
      inverted: ${red_led_inverted}
